### PR TITLE
Use of "self" in callables is deprecated

### PR DESCRIPTION
**Pull request by a2exfr**

### CODE REVIEW

**Comment by gtbu** [comment]
Yes - this is first for php8.2 - but i will use it  (functions also with php 8.1) - thanks !

(If You want to support me and are so fit : The 'Install from web' doesnt function with php 8.2 - the archive-functions is-callable etc. have false parameters for php8.2 (since TP4.6) 

It needs to be rewritten (this was first planned for summer , because i plan to add scssphp 1.11 first and then crush-prefixer as choice in addon.ini and a Btrap5-theme )

**Comment by a2exfr** [comment]
I'm not sure what exactly doesn't work, but I tried this fork on PHP 8.2 and everything seems to work fine, except for some errors in scssphp

**Comment by gtbu** [comment]
include/tool/Archive.php  deprecated 👍

**Comment by a2exfr** [comment]
Unfortunately I can't reproduce this error, plugin installation works fine for me on php 8.2.0

**Comment by gtbu** [comment]
Sorry - i had an experimental code:
I get during installation of a plugin (php8.2)

ExecInfo() Fatal Error: call_user_func_array(): Argument https://github.com/gtbu/Typesetter-5.3-p8/issues/1 ($callback) must be a valid callback, first array member is not a valid class name or object
in: H:\xampp82\xampp\htdocs\tp53p8\include\tool\Archive.php
on line: 153

**Comment by a2exfr** [comment]
so far I have added a small  link fix ->    [here](https://github.com/gtbu/Typesetter-5.3-p8/pull/12/commits/7c71dbb8052b9d2f1e69298786b97268ac07c7d7#diff-6e1e1e6c30b22aeba94a4a8f7f2a63ddac27f63d78ccee2fdc8ae7406a8893bcR1277)

reason:
image

**Review by gtbu — APPROVED** [review]

**Comment by gtbu** [comment]
I installed Your new version : The above error 

ExecInfo() Fatal Error: call_user_func_array(): Argument https://github.com/gtbu/Typesetter-5.3-p8/issues/1 ($callback) must be a valid callback, first array member is not a valid class name or object
in: H:\xampp82\xampp\htdocs\tp53p8\include\tool\Archive.php
on line: 153

(still much to do : I think i will publish scssphp until the weekend . Mr Krausz has added the vendor prefixes manually - i tried tat for  Bootstrap 5.2 and gave up :-  the rem to px doesnt function with the new compiler.)

**Comment by gtbu** [comment]
I tested on my vserver :  ExecInfo() Fatal Error: call_user_func_array(): Argument https://github.com/gtbu/Typesetter-5.3-p8/issues/1 ($callback) must be a valid callback, first array member is not a valid class name or object **does not appear** . But i will keep in in the Backhead - it should not come up under Xampp.

Can You do me a favour and update 'catalog easy' und others at typesettercms.com. I updated several plugins - under : Support - until i was banned for a week.....Why they still offer Typesetter 5.1 is not understandable for me....?

**Comment by gtbu** [comment]
Applicated commit

**Pull request closed without merging**
